version: '3.1.2'

services:
  java-app:
    image: todolist-api
    depends_on:
      - db
    environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todolist
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=password
          - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - "8081:8081"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist